/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Notepad;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    public void testAddTodoWhenListFull(){
        Todo todo = new Todo("test");
        TodoList todoList = new TodoList(0);
        int info = todoList.addTodo(todo);
        Assertions.assertEquals(-1, info);
    }

    @Test
    public void testAddTodoWithIllegalTodo(){
        Todo todo = new Todo();
        TodoList todoList = new TodoList(1);
        int info = todoList.addTodo(todo);
        Assertions.assertEquals(-2, info);
    }

    @Test
    public void testFinishTodoNotInList(){
        Todo todo = new Todo("test in list");
        TodoList todoList = new TodoList(1);
        todoList.addTodo(todo);
        int info = todoList.finishTodo("test not in list");
        Assertions.assertEquals(-1, info);
    }

    @Test
    public void testFinishTodoInList(){
        Todo todo = new Todo("test in list");
        TodoList todoList = new TodoList(1);
        todoList.addTodo(todo);
        int info = todoList.finishTodo("test in list");
        Assertions.assertEquals(1, info);
    }

    @Test
    public void testDeleteTodoWhenListFull(){
        Todo todo = new Todo("test");
        TodoList todoList = new TodoList(5);
        todoList.addTodo(todo);
        int info = todoList.deleteTodo(todo.getTitle());
        Assertions.assertEquals(1, info);
    }
}
